### ISSUE TITLE
No such file to load -- tasks/mactag.rake

### ISSUE THREAD

**Issue by crawlik** [rejeep/mactag#6]
Looks like adding mactag ruins rake command in my rails project. Check out call stack. 

Rails 3.0.9
mactag 0.7.0 

$ rake -vT
rake aborted!
No such file to load -- tasks/mactag.rake
org/jruby/RubyKernel.java:1063:in `load'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in`load'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in`new_constants_in'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:595:in `new_constants_in'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in`load_dependency'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/home/alex/.rvm/gems/jruby-1.6.2@report/gems/mactag-0.7.0/lib/mactag/railtie.rb:4:in`Railtie'

```
1 module Mactag
2   class Railtie < Rails::Railtie
3     rake_tasks do
4       load 'tasks/mactag.rake'
5     end
6   end
7 end
```

**Comment by rejeep** [comment]
Hi,

The rake task was removed in version `0.7.0`. You now use the `mactag` binary instead. Check out the `README` for more information!

**Comment by crawlik** [comment]
Looks like gem distributed from `:rubygems` still includes `railtie.rb` that tries loading non-existing rake tasks. Try to download it and unzip it and you will see it.

**Comment by rejeep** [comment]
Damn it! See https://github.com/rejeep/mactag/commit/284a93edb36b1eb7ffdcd802fea0442a49313259

Thanks for reporting! Version `0.7.1` is out with the fix!

**Comment by crawlik** [comment]
Thanks for the quick fix.
